// <auto-generated />
using System;
using Balanced_Gaming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balanced_Gaming.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Balanced_Gaming.Models.Game", b =>
                {
                    b.Property<int>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("addedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("gameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isManuallyAdded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("processName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("steamAppId")
                        .HasColumnType("INTEGER");

                    b.HasKey("gameId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.GameReminderException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("gameReminderExceptions");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.GameSession", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("breakRemindersDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("breakRemindersShown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("breakTaken")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("gameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("sessionId");

                    b.HasIndex("gameId");

                    b.HasIndex("userId");

                    b.ToTable("gameSessions");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.MoodAssessment", b =>
                {
                    b.Property<int>("assessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("assessmentTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("energyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("focusLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("moodScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("motivation")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("satisfaction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("sessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stressLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("wellbeingImpact")
                        .HasColumnType("INTEGER");

                    b.HasKey("assessmentId");

                    b.HasIndex("sessionId");

                    b.HasIndex("userId");

                    b.ToTable("moodAssessments");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.ReminderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnoozeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("reminderSettings");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("breakRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("defaultBreakRemindersMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("moodTrackingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.GameReminderException", b =>
                {
                    b.HasOne("Balanced_Gaming.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.GameSession", b =>
                {
                    b.HasOne("Balanced_Gaming.Models.Game", "game")
                        .WithMany("gameSessions")
                        .HasForeignKey("gameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balanced_Gaming.Models.User", "user")
                        .WithMany("gameSessions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("game");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.MoodAssessment", b =>
                {
                    b.HasOne("Balanced_Gaming.Models.GameSession", "gameSession")
                        .WithMany()
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Balanced_Gaming.Models.User", "user")
                        .WithMany("moodAssessments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gameSession");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.Game", b =>
                {
                    b.Navigation("gameSessions");
                });

            modelBuilder.Entity("Balanced_Gaming.Models.User", b =>
                {
                    b.Navigation("gameSessions");

                    b.Navigation("moodAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
